name: tests

on:
  push:
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends ca-certificates git python3
      - uses: actions/checkout@v5
      - run: python3 -m unittest discover -s tests -b
